server:
  port: 1001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka/


  #禁用自我保护机制
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
