
server:
  port: 80
spring:
  cloud:
    consul:
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      host: localhost
  application:
    name: consul-service-order
