
server:
  port: 9002
spring:
  application:
    name: cloud-payment-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

