
server:
  port: 8006
spring:
  cloud:
    consul:
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}
      host: localhost
  application:
    name: consul-service-payment

