
server:
  port: 80
spring:
  application:
    name: cloud-openfeign-order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka,http://127.0.0.1:1001/eureka


logging:
  level:
  #feign日志以什么级别监控哪个接口
    com.newland.cloud.springcloudorderopenfen.service.OpenService: debug
