
server:
  port: 9527
spring:
  application:
    name: spirngcloud-getway
  cloud:
    gateway:
      routes:
      -   id: payment_routh
          #uri: http://127.0.0.1:8002
          uri: lb://CLOUD-PAYMENT-SERVICE #lb 代表loadBalanced 基于服务注册的负载均衡
          predicates:
              Path=/payment/get/**

      -   id: payment_routh
          uri: http://127.0.0.1:8002
          predicates:
          -    Path=/payment/lb/**
               

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
    fetch-registry: true
    register-with-eureka: true


